### ISSUE TITLE
How to activate it?

### ISSUE THREAD

**Issue by michaldybczak** [sanjay-kr-commit/panelTransparencyToggleForPlasma6#1]
I added it to a Plasma 6 panel and now what? It is invisible, so I can't even find it to right-click it. Or maybe it supposed to make the panel invisible just by adding it?

**Comment by sanjay-kr-commit** [comment]
Sorry for late reply that's the intended behaviour

To make it visible
Goto to edit mode and the button will be visible than
Either click on it to make it temporarily visible or remove it to revert changes

**Comment by sanjay-kr-commit** [comment]
Added some option to change this behaviour in new version
